from __future__ import annotations
from typing import Optional, ClassVar, Iterable, Iterator


class VoxInternerU8: ...
class VoxInternerU16: ...
class VoxInternerU32: ...
class VoxInternerI32: ...

# -----------------------------------------------------------------------------
# BlockId
# -----------------------------------------------------------------------------
class BlockId:
    INVALID: ClassVar[BlockId]
    EMPTY: ClassVar[BlockId]
    MAX_INDEX: ClassVar[int]
    MAX_GENERATION: ClassVar[int]

    def __new__(cls) -> BlockId: ...

    @staticmethod
    def from_raw(raw: int) -> BlockId: ...

    @staticmethod
    def new_leaf(index: int, generation: int) -> BlockId: ...

    @staticmethod
    def new_branch(index: int, generation: int, types: int, mask: int) -> BlockId: ...

    def index(self) -> int: ...
    def generation(self) -> int: ...
    def types(self) -> int: ...
    def mask(self) -> int: ...

    def has_child(self, child_index: int) -> bool: ...
    def is_leaf(self) -> bool: ...
    def is_branch(self) -> bool: ...
    def is_invalid(self) -> bool: ...
    def is_valid(self) -> bool: ...
    def is_empty(self) -> bool: ...
    def raw(self) -> int: ...

    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


# -----------------------------------------------------------------------------
# Children [BlockId; 8]
# -----------------------------------------------------------------------------
class Children:
    def __new__(cls) -> Children: ...

    @staticmethod
    def from_list(list: list[BlockId]) -> Children: ...

    def to_list(self) -> list[BlockId]: ...

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> BlockId: ...
    def __setitem__(self, index: int, value: BlockId) -> None: ...
    def __repr__(self) -> str: ...


# -----------------------------------------------------------------------------
# PatternsHashmap
# -----------------------------------------------------------------------------
class PatternsHashmap:
    def __new__(cls) -> PatternsHashmap: ...

    def insert(self, hash: int, block_id: BlockId) -> None: ...
    def get(self, hash: int) -> Optional[BlockId]: ...
    def remove(self, hash: int) -> Optional[BlockId]: ...
    def clear(self) -> None: ...
    def is_empty(self) -> bool: ...
    def __len__(self) -> int: ...

    def keys(self) -> list[int]: ...
    def values(self) -> list[BlockId]: ...
    def items(self) -> list[tuple[int, BlockId]]: ...

    def reserve(self, additional: int) -> None: ...

    def __contains__(self, hash: int) -> bool: ...
    def __getitem__(self, hash: int) -> BlockId: ...
    def __setitem__(self, hash: int, block_id: BlockId) -> None: ...
    def __delitem__(self, hash: int) -> None: ...

    def __repr__(self) -> str: ...


# -----------------------------------------------------------------------------
# Lod
# -----------------------------------------------------------------------------
class Lod:
    def __new__(cls, lod: int) -> Lod: ...
    def lod(self) -> int: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


# -----------------------------------------------------------------------------
# MaxDepth
# -----------------------------------------------------------------------------
class MaxDepth:
    def __new__(cls, max: int) -> MaxDepth: ...
    def max(self) -> int: ...
    def as_usize(self) -> int: ...
    def for_lod(self, lod: Lod) -> MaxDepth: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


# -----------------------------------------------------------------------------
# TraversalDepth
# -----------------------------------------------------------------------------
class TraversalDepth:
    def __new__(cls, current: int, max: int) -> TraversalDepth: ...
    def current(self) -> int: ...
    def max(self) -> int: ...
    def increment(self) -> TraversalDepth: ...
    def decrement(self) -> TraversalDepth: ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...


# -----------------------------------------------------------------------------
# Batch
# -----------------------------------------------------------------------------
class BatchU8:
    def __new__(cls, max_depth: int) -> None: ...
    def fill(self, interner: "VoxInternerU8", value: int) -> None: ...
    def set(self, interner: "VoxInternerU8", x: int, y: int, z: int, value: int) -> None: ...
    def clear(self, interner: "VoxInternerU8") -> None: ...
    def just_set(self, x: int, y: int, z: int, value: int) -> bool: ...
    def size(self) -> int: ...
    def has_patches(self) -> bool: ...
    def to_fill(self) -> Optional[int]: ...

class BatchU16:
    def __new__(cls, max_depth: int) -> None: ...
    def fill(self, interner: "VoxInternerU16", value: int) -> None: ...
    def set(self, interner: "VoxInternerU16", x: int, y: int, z: int, value: int) -> None: ...
    def clear(self, interner: "VoxInternerU16") -> None: ...
    def just_set(self, x: int, y: int, z: int, value: int) -> bool: ...
    def size(self) -> int: ...
    def has_patches(self) -> bool: ...
    def to_fill(self) -> Optional[int]: ...

class BatchU32:
    def __new__(cls, max_depth: int) -> None: ...
    def fill(self, interner: "VoxInternerU32", value: int) -> None: ...
    def set(self, interner: "VoxInternerU32", x: int, y: int, z: int, value: int) -> None: ...
    def clear(self, interner: "VoxInternerU32") -> None: ...
    def just_set(self, x: int, y: int, z: int, value: int) -> bool: ...
    def size(self) -> int: ...
    def has_patches(self) -> bool: ...
    def to_fill(self) -> Optional[int]: ...

class BatchI32:
    def __new__(cls, max_depth: int) -> None: ...
    def fill(self, interner: "VoxInternerI32", value: int) -> None: ...
    def set(self, interner: "VoxInternerI32", x: int, y: int, z: int, value: int) -> None: ...
    def clear(self, interner: "VoxInternerI32") -> None: ...
    def just_set(self, x: int, y: int, z: int, value: int) -> bool: ...
    def size(self) -> int: ...
    def has_patches(self) -> bool: ...
    def to_fill(self) -> Optional[int]: ...


__all__ = [
    "BlockId",
    "Children",
    "PatternsHashmap",
    "Lod",
    "MaxDepth",
    "TraversalDepth",
    "BatchU8",
    "BatchU16",
    "BatchU32",
    "BatchI32",
]