from __future__ import annotations
from typing import ClassVar, Optional

# 导入依赖类型
class BlockId: ...
class Children: ...

# -----------------------------------------------------------------------------
# Interner 常量类
# -----------------------------------------------------------------------------
class InternerConstants:
    MAX_ALLOWED_DEPTH: ClassVar[int]
    MAX_CHILDREN: ClassVar[int]
    NODE_TYPE_LEAF: ClassVar[int]
    NODE_TYPE_BRANCH: ClassVar[int]
    PATTERNS_TYPE_BRANCH: ClassVar[int]
    PATTERNS_TYPE_LEAF: ClassVar[int]
    CHILD_ABSENT: ClassVar[int]
    PREALLOCATED_STACK_SIZE: ClassVar[int]

    def __new__(cls) -> None: ...


# -----------------------------------------------------------------------------
# PatternsHashmap
# -----------------------------------------------------------------------------
class PatternsHashmap:
    def __new__(cls) -> PatternsHashmap: ...

    def insert(self, hash: int, block_id: BlockId) -> None: ...
    def get(self, hash: int) -> Optional[BlockId]: ...
    def contains_key(self, hash: int) -> bool: ...
    def remove(self, hash: int) -> Optional[BlockId]: ...
    def clear(self) -> None: ...
    def len(self) -> int: ...
    def is_empty(self) -> bool: ...


# -----------------------------------------------------------------------------
# VoxInterner U8
# -----------------------------------------------------------------------------
class VoxInternerU8:
    @staticmethod
    def with_memory_budget(budget: int) -> VoxInternerU8: ...

    @staticmethod
    def node_size() -> int: ...
    def capacity(self) -> int: ...
    def patterns_empty(self) -> bool: ...

    # 读取与子节点
    def get_value(self, block_id: BlockId) -> int: ...
    def get_children(self, block_id: BlockId) -> Children: ...
    def get_child_id(self, block_id: BlockId, index: int) -> BlockId: ...
    def get_ref(self, block_id: BlockId) -> int: ...

    # 引用计数
    def inc_ref(self, block_id: BlockId) -> None: ...
    def dec_ref(self, block_id: BlockId) -> bool: ...
    def inc_ref_by(self, block_id: BlockId, count: int) -> None: ...
    def dec_ref_by(self, block_id: BlockId, count: int) -> None: ...
    def dec_ref_recursive(self, block_id: BlockId) -> None: ...

    # 子节点引用批量操作
    def inc_child_refs(self, children: Children, index: int) -> None: ...
    def inc_all_child_refs(self, children: Children) -> None: ...
    def dec_child_refs(self, children: Children) -> None: ...

    # 节点创建
    def get_or_create_leaf(self, value: int) -> BlockId: ...
    def get_or_create_branch(self, children: Children, types: int, mask: int) -> BlockId: ...
    def create_empty_branch(self) -> BlockId: ...
    def create_branch(self, children: Children, types: int, mask: int) -> BlockId: ...
    def update_branch(
        self,
        block_id: BlockId,
        child_id: BlockId,
        child_index: int,
        types: int,
        mask: int
    ) -> BlockId: ...

    # 反序列化
    def deserialize_leaf(self, index: int, value: int) -> BlockId: ...
    def deserialize_branch(
        self,
        block_id: BlockId,
        children: Children,
        types: int,
        mask: int,
        average: int
    ) -> None: ...

    # 校验与统计
    def is_valid_block_id(self, block_id: BlockId) -> bool: ...
    def ensure_valid_children(self, children: Children) -> None: ...
    def count_nodes(self, block_id: BlockId) -> int: ...

    # 内存统计（feature-gated）
    @property
    def stats(self) -> InternerStats: ...


# -----------------------------------------------------------------------------
# VoxInterner U16
# -----------------------------------------------------------------------------
class VoxInternerU16(VoxInternerU8):
    @staticmethod
    def with_memory_budget(budget: int) -> VoxInternerU16: ...


# -----------------------------------------------------------------------------
# VoxInterner U32
# -----------------------------------------------------------------------------
class VoxInternerU32(VoxInternerU8):
    @staticmethod
    def with_memory_budget(budget: int) -> VoxInternerU32: ...


# -----------------------------------------------------------------------------
# VoxInterner I32 (线程安全)
# -----------------------------------------------------------------------------
class VoxInternerI32:
    @staticmethod
    def with_memory_budget(budget: int) -> VoxInternerI32: ...

    @staticmethod
    def node_size() -> int: ...
    def capacity(self) -> int: ...
    def patterns_empty(self) -> bool: ...

    # 读取与子节点
    def get_value(self, block_id: BlockId) -> int: ...
    def get_children(self, block_id: BlockId) -> Children: ...
    def get_child_id(self, block_id: BlockId, index: int) -> BlockId: ...
    def get_ref(self, block_id: BlockId) -> int: ...

    # 引用计数
    def inc_ref(self, block_id: BlockId) -> None: ...
    def dec_ref(self, block_id: BlockId) -> bool: ...
    def inc_ref_by(self, block_id: BlockId, count: int) -> None: ...
    def dec_ref_by(self, block_id: BlockId, count: int) -> None: ...
    def dec_ref_recursive(self, block_id: BlockId) -> None: ...

    # 子节点引用批量操作
    def inc_child_refs(self, children: Children, index: int) -> None: ...
    def inc_all_child_refs(self, children: Children) -> None: ...
    def dec_child_refs(self, children: Children) -> None: ...

    # 节点创建
    def get_or_create_leaf(self, value: int) -> BlockId: ...
    def get_or_create_branch(self, children: Children, types: int, mask: int) -> BlockId: ...
    def create_empty_branch(self) -> BlockId: ...
    def create_branch(self, children: Children, types: int, mask: int) -> BlockId: ...
    def update_branch(
        self,
        block_id: BlockId,
        child_id: BlockId,
        child_index: int,
        types: int,
        mask: int
    ) -> BlockId: ...

    # 反序列化
    def deserialize_leaf(self, index: int, value: int) -> BlockId: ...
    def deserialize_branch(
        self,
        block_id: BlockId,
        children: Children,
        types: int,
        mask: int,
        average: int
    ) -> None: ...

    # 校验与统计
    def is_valid_block_id(self, block_id: BlockId) -> bool: ...
    def ensure_valid_children(self, children: Children) -> None: ...
    def count_nodes(self, block_id: BlockId) -> int: ...

    # 内存统计
    @property
    def stats(self) -> InternerStats: ...

    # 线程共享
    def clone_handle(self) -> VoxInternerI32: ...


# -----------------------------------------------------------------------------
# InternerStats
# -----------------------------------------------------------------------------
class InternerStats:
    @property
    def requested_budget(self) -> int: ...
    @property
    def actual_budget(self) -> int: ...
    @property
    def node_size(self) -> int: ...
    @property
    def nodes_capacity(self) -> int: ...
    @property
    def total_allocations(self) -> int: ...
    @property
    def total_deallocations(self) -> int: ...
    @property
    def allocated_nodes(self) -> int: ...
    @property
    def recycled_nodes(self) -> int: ...
    @property
    def alive_nodes(self) -> int: ...
    @property
    def patterns(self) -> int: ...
    @property
    def total_cache_hits(self) -> int: ...
    @property
    def total_cache_misses(self) -> int: ...
    @property
    def branch_cache_hits(self) -> int: ...
    @property
    def branch_cache_misses(self) -> int: ...
    @property
    def leaf_cache_hits(self) -> int: ...
    @property
    def leaf_cache_misses(self) -> int: ...
    @property
    def collapsed_branches(self) -> int: ...
    @property
    def leaf_nodes(self) -> int: ...
    @property
    def branch_nodes(self) -> int: ...
    @property
    def max_alive_nodes(self) -> int: ...
    @property
    def max_node_id(self) -> int: ...
    @property
    def max_branch_ref_count(self) -> int: ...
    @property
    def max_leaf_ref_count(self) -> int: ...
    @property
    def max_generation(self) -> int: ...
    @property
    def generations_overflows(self) -> int: ...

    def __repr__(self) -> str: ...


__all__ = [
    "InternerConstants",
    "PatternsHashmap",
    "VoxInternerU8",
    "VoxInternerU16",
    "VoxInternerU32",
    "VoxInternerI32",
    "InternerStats",
]