from __future__ import annotations
from typing import Optional, Tuple


class BlockId: ...
class BatchU8: ...
class BatchU16: ...
class BatchU32: ...
class BatchI32: ...

class VoxInternerU8: ...
class VoxInternerU16: ...
class VoxInternerU32: ...
class VoxInternerI32: ...

# -----------------------------------------------------------------------------
# Aabb2d
# -----------------------------------------------------------------------------
class Aabb2d:
    @staticmethod
    def with_min_max(min: Tuple[float, float], max: Tuple[float, float]) -> Aabb2d: ...
    @staticmethod
    def with_position_and_size(pos: Tuple[float, float], size: Tuple[float, float]) -> Aabb2d: ...

    @property
    def min(self) -> Tuple[float, float]: ...
    @property
    def max(self) -> Tuple[float, float]: ...

    def size(self) -> Tuple[float, float]: ...
    def union(self, other: Aabb2d) -> Aabb2d: ...
    def contains(self, point: Tuple[float, float]) -> bool: ...
    def intersects(self, other: Aabb2d) -> bool: ...

    def __repr__(self) -> str: ...

# -----------------------------------------------------------------------------
# VoxTreeU8
# -----------------------------------------------------------------------------
class VoxTreeU8:
    def __new__(cls, max_depth: int) -> VoxTreeU8: ...

    # Batch
    def create_batch(self) -> BatchU8: ...
    def apply_batch(self, interner: VoxInternerU8, batch: BatchU8) -> None: ...

    # 读写
    def get(self, interner: VoxInternerU8, x: int, y: int, z: int) -> Optional[int]: ...
    def set(self, interner: VoxInternerU8, x: int, y: int, z: int, value: int) -> bool: ...
    def fill(self, interner: VoxInternerU8, value: int) -> None: ...
    def clear(self, interner: VoxInternerU8) -> None: ...

    # Config
    def max_depth(self, lod: int) -> int: ...
    def voxels_per_axis(self, lod: int) -> int: ...

    # State
    def is_empty(self) -> bool: ...
    def is_leaf(self) -> bool: ...

    # Dirty
    def is_dirty(self) -> bool: ...
    def mark_dirty(self) -> None: ...
    def clear_dirty(self) -> None: ...

    # Root
    def get_root_id(self) -> BlockId: ...
    def set_root_id(self, interner: VoxInternerU8, root_id: BlockId) -> None: ...

    # Mesh / Export
    def to_vec(self, interner: VoxInternerU8, lod: int) -> list[int]: ...

# -----------------------------------------------------------------------------
# VoxTreeU16
# -----------------------------------------------------------------------------
class VoxTreeU16:
    def __new__(cls, max_depth: int) -> VoxTreeU16: ...

    # Batch
    def create_batch(self) -> BatchU16: ...
    def apply_batch(self, interner: VoxInternerU16, batch: BatchU16) -> None: ...

    # 读写
    def get(self, interner: VoxInternerU16, x: int, y: int, z: int) -> Optional[int]: ...
    def set(self, interner: VoxInternerU16, x: int, y: int, z: int, value: int) -> bool: ...
    def fill(self, interner: VoxInternerU16, value: int) -> None: ...
    def clear(self, interner: VoxInternerU16) -> None: ...

    # Config
    def max_depth(self, lod: int) -> int: ...
    def voxels_per_axis(self, lod: int) -> int: ...

    # State
    def is_empty(self) -> bool: ...
    def is_leaf(self) -> bool: ...

    # Dirty
    def is_dirty(self) -> bool: ...
    def mark_dirty(self) -> None: ...
    def clear_dirty(self) -> None: ...

    # Root
    def get_root_id(self) -> BlockId: ...
    def set_root_id(self, interner: VoxInternerU16, root_id: BlockId) -> None: ...

    # Mesh / Export
    def to_vec(self, interner: VoxInternerU16, lod: int) -> list[int]: ...

# -----------------------------------------------------------------------------
# VoxTreeU32
# -----------------------------------------------------------------------------
class VoxTreeU32:
    def __new__(cls, max_depth: int) -> VoxTreeU32: ...

    # Batch
    def create_batch(self) -> BatchU32: ...
    def apply_batch(self, interner: VoxInternerU32, batch: BatchU32) -> None: ...

    # 读写
    def get(self, interner: VoxInternerU32, x: int, y: int, z: int) -> Optional[int]: ...
    def set(self, interner: VoxInternerU32, x: int, y: int, z: int, value: int) -> bool: ...
    def fill(self, interner: VoxInternerU32, value: int) -> None: ...
    def clear(self, interner: VoxInternerU32) -> None: ...

    # Config
    def max_depth(self, lod: int) -> int: ...
    def voxels_per_axis(self, lod: int) -> int: ...

    # State
    def is_empty(self) -> bool: ...
    def is_leaf(self) -> bool: ...

    # Dirty
    def is_dirty(self) -> bool: ...
    def mark_dirty(self) -> None: ...
    def clear_dirty(self) -> None: ...

    # Root
    def get_root_id(self) -> BlockId: ...
    def set_root_id(self, interner: VoxInternerU32, root_id: BlockId) -> None: ...

    # Mesh / Export
    def to_vec(self, interner: VoxInternerU32, lod: int) -> list[int]: ...

__all__ = [
    "Aabb2d",
    "VoxTreeU8",
    "VoxTreeU16",
    "VoxTreeU32",
]